import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import textwrap

df = pd.read_excel("data.xlsx")
df.columns = df.columns.str.lower().str.strip()
available_cols = df.columns
required_cols = ['title', 'subreddit', 'score', 'num_comments']
df = df[[col for col in required_cols if col in available_cols]].dropna()

top_subreddits = df['subreddit'].value_counts().head(10)
plt.figure(figsize=(8, 5))
sns.barplot(x=top_subreddits.values, y=top_subreddits.index, palette="viridis")
plt.title("Top Subreddits by Post Count", fontsize=12)
plt.xlabel("Number of Posts", fontsize=10)
plt.ylabel("Subreddit", fontsize=10)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.show()

top_posts = df.sort_values(by='score', ascending=False).head(10).copy()
top_posts['wrapped_title'] = top_posts['title'].apply(lambda x: "\n".join(textwrap.wrap(x, 40)))
plt.figure(figsize=(8, 5))
sns.barplot(x='score', y='wrapped_title', data=top_posts, palette='rocket')
plt.title("Top 10 Most Upvoted Posts", fontsize=12)
plt.xlabel("Upvotes", fontsize=10)
plt.ylabel("Post Title", fontsize=10)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.show()

top_comments = df.sort_values(by='num_comments', ascending=False).head(10).copy()
top_comments['wrapped_title'] = top_comments['title'].apply(lambda x: "\n".join(textwrap.wrap(x, 40)))
plt.figure(figsize=(8, 5))
sns.barplot(x='num_comments', y='wrapped_title', data=top_comments, palette='mako')
plt.title("Top 10 Most Commented Posts", fontsize=12)
plt.xlabel("Comments", fontsize=10)
plt.ylabel("Post Title", fontsize=10)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.scatterplot(x='score', y='num_comments', hue='subreddit', data=df, palette='tab10', legend='full', s=40)
plt.title("Upvotes vs. Comments Correlation", fontsize=12)
plt.xlabel("Upvotes", fontsize=10)
plt.ylabel("Comments", fontsize=10)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0., fontsize=7)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.histplot(df['num_comments'], bins=30, kde=True, color='purple')
plt.title("Comment Count Distribution", fontsize=12)
plt.xlabel("Number of Comments", fontsize=10)
plt.ylabel("Frequency", fontsize=10)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8, 5))
sns.boxplot(data=df[['score', 'num_comments']], palette="pastel")
plt.title("Engagement Distribution: Upvotes vs Comments", fontsize=12)
plt.xticks(fontsize=8)
plt.yticks(fontsize=8)
plt.tight_layout()
plt.show()
